apiVersion: v1
kind: ReplicationController
metadata:
  name: bitlab-voteview
  labels:
    name: bitlab-voteview
spec:
  template:
    metadata:
      name: bitlab-voteview
      labels:
        name: bitlab-voteview
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: bitlab-voteview-access-token
      containers:
        - name: bitlab-voteview
          image: gcr.io/littlebits-electronics/bitlab-voteview:latest
          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: /etc/secrets
